### ISSUE TITLE
update-facebook-events.sh complains about path

### ISSUE THREAD

**Issue by pseudobacon** [bxabi/facebook-events-ics#1]
I'm running into an issue with running the shell script

![image](https://user-images.githubusercontent.com/12183854/73325419-8fa03d80-42a2-11ea-9939-a18c24ac114d.png)

**Comment by bxabi** [comment]
Hi! I think I see what the problem was, I adapted the file.
In the previous version it was necessary to include the path where the divide script is located. If you update it it should work directly if both files are in the current folder. And I added a comment to show where to insert the path if it is somewhere else (when running with cron)

**Comment by pseudobacon** [comment]
Ok. That fixed it
